eliotjang/Movolleh-Movie-Website

index.html, src/render.js, style/index.css
`render.js`
- `$movie` 변수에 `innerHTML` 속성을 사용하여 넣은 영화 제목, 내용 요약, 평점을 `style = 'display : none'`처리 하여 랜딩 페이지에서 미출력
- `addEventListener("mouseenter",  )` 함수를 사용하여 마우스 오버 시 `printTitle()` 콜백함수 호출
- `addEventListener("mouseleave",  )` 함수를 사용하여 마우스 아웃 시 `deleteTitle()` 콜백함수 호출
- 영화 제목을 출력하는 `printTitle()` 함수 구현
- 영화 제목을 제거하는 `deleteTitle()` 함수 구현
`index.css`
- font-size 속성으로 폰트 조정
- 현재 구현되어있는 마우스 오버 시 카드가 올라가고 아웃 시 카드가 내려가는 애니메이션이 제목이 출력되는 기능과 어색하지 않아  기존 애니메이션 사용하는 것으로 임의 결정
<figure class="half">
<a href="link"><img src="https://github.com/eliotjang/Movolleh-Movie-Website/assets/37320831/f0065e08-70e2-4bb8-a4c2-1a03597254b4"></a>
<a href="link"><img src="https://github.com/eliotjang/Movolleh-Movie-Website/assets/37320831/75b7b500-4c59-4600-80f7-93afb285bd91"></a>
</figure>
=> Update - 랜딩 페이지 영화 카드 오버 시 제목 및 애니메이션 기능 추가

movieDetail.html, style/movieDetail.css
전체 틀은 이렇게 잡아놓은상태입니다. 
완벽하지 않으나 추후 수정사항은 필요해보입니다. 
- 스크롤 작동하는것 확인 완료 했습니다.
- 현재 보여지고 있는 모든 데이터는 하드 코딩 되어있습니다.
- css 가 겹치는것이 있어보이는데 추후에 확인되는 대로 수정 하겠습니다.
=> [Add]-영화 상세페이지 기초HTML , CSS 작성

src/render.js
```
window.location.href = `movieDetail.html?id=${movie.id}`;
```
```
const urlParams = new URLSearchParams(location.search).get("id");
console.log(urlParams);
```
=> [Update] - index.html 에서영화 카드 선택시 id를 포함하여 detail페이지로 이동

src/render.js, style/index.css
- 이제 더이상 영화 내용 영화 별점을 렌더링하지않습니다.
- display: none - > block 은 transition 이 적용안되는 사실을 발견하였습니다. 차선책으로 movieTitle 백그라운드 색을 전체 바디의 백그라운드 색과 동일하게 하여 마치 없는 것처럼 적용하였습니다. 그후 transition을통해 색을 백그라운드 색을 변경해주도록 하였습니다.
- JS 파일로 작성되어 있던 마우스 오버 효과를 css 파일로 대체하였습니다.
=> [Update] - 카드오버시 css transition 추가

movieDetail.html, src/crewDetail/crewCard.js, src/tmdb-api/api.js, style/movieDetail.css
`Update api.js`
- `fetchCreditData()` 함수로 TMDB - Credit open API fetch
- `URLSearchParams()` 함수로 URL에서 Query String 추출
`Add crewCard.js`
- `introduceCard()` 함수로 카드 리스트 구현 수행
- `introduceDirector()` 함수로 감독 리스트 구현
- `introduceCast()` 함수로 출연진 리스트 구현
- 변수명 Camel Case 수정
- 전역으로 작성된 변수, 함수 Code Refactoring
- JavaScript 파일명 수정
=> [Update] - 감독 및 출연진 카드 리스트 추가

movieDetail.html, src/render.js, src/similarMovies.js, src/tmdb-api/api.js, style/similarMoviesStyle.css
- `fetchSimilarMoviesData` 함수 추가
- 추천 영화 카드 리스트 기능 구현
- 추천 영화 카드 클릭시 새로운 상세 페이지 생성
- `border-radius`를 `10px`로 조정
- 기능구현을 위한 `moviesGrid class` 삭제
- 코드 리팩토링
- URL Query String 사용
- 추천 영화 마우스 오버 시 제목 출력
- 추천 영화 포스터 모서리 조정
=> [Update] - 상세페이지 우측 추천 영화 카드 리스트 UI 기능 구현

movieDetail.html, src/crewDetail/crewCard.js, src/crewDetail/movieDetail.js, src/movieDetail.js, src/tmdb-api/api.js, style/movieDetail.css
`Update api.js`
- `fetchDetailData()` 함수로 TMDB - Movie Detail open API fetch
- `URLSearchParams()` 함수로 URL에서 Query String 추출
- `detailCard()` 함수로 영화 세부 사항 출력 구현
- `getPoster()` 함수로 포스터 출력 구현
- `getMovieTitle()` 함수로 영화제목 출력 구현
- `getMovieOverview()` 함수로 영화오버뷰 출력 구현
- 포스터, 감독, 배우 프로필 사진 보더 처리
- 포스터, 영화제목, 오버뷰 배치를 자연스럽도록 재배치 
- 상세페이지 body의 background color를 검은색으로 수정
- 폰트 크기 수정, 폰트 색상 베이지 색으로 수정
=> 8 update 상세 페이지 좌측 영화 포스터 제목 내용 요약 기능 구현

index.html, src/render.js, style/index.css
- 좌측 상단 "MOVOLLEH" 홈 버튼 추가   
- 홈 버튼 클릭시 홈으로 이동하는 기능 구현
- 우측 상단 "검색란" input 위치 및 크기 조정
=> [Add] - 랜딩 페이지 헤더 UI

movieDetail.html, src/crewDetail/movieDetail.js, style/index.css, style/movieDetail.css
* 헤더 UI는 랜딩페이지와 동일하게   
* ANVOLLEH 버튼 추가 및 검색란 삭제   
* 랜딩 페이지 및 상세 페이지 홈버튼  호버기능 추가
=> [Update] - 좌측 상단 홈 복귀 버튼 및 헤더 UI 구성

movieDetail.html, src/crewDetail/crewCard.js, style/movieDetail.css
* 기존 감독과 출연진이 2줄로 나누어져 있던 것을 1줄로 정렬함
* 따라서 출연진이 정렬되어있던 div가 공백이 되었으므로 삭제함
=> [Fix] - 감독 및 출연진 1줄 정렬

style/movieDetail.css
* 상하스크롤 바를 생기게 만드는 원인이었던 height 값을 좀 더 여유롭게 수정
* 좌우스크롤 바도 되도록 생기지 않게끔 width 값을 좀 더 여유롭게 수정
- 단, 영화 제목이 너무 긴 경우는 어쩔 수 없이 좌우스크롤 바 생성되는 것 같음
=> [Bugfix] - 감독 및 출연진 우측 스크롤 바 수정

src/similarMovies.js
- 해당 영화 개요가 빈 문자열인 경우 추천 영화에서 유효성 검사 후 미출력
- 유효성 검사 이후 영화가 추천 영화에서 미출력 되었지만 클릭하면 유효성 검사를 통과하지 못한 영화의 상세 페이지가 생성
=> [Bugfix] - 추천 영화 클릭 시 해당 영화 감독 및 출연진 포스터 미출력

index.html
=> [Update] - 팀 소개 배경 및 소개글 작성-TEST

index.html, style/index.css
포스터 페이지 및 포스터 페이지 내 팀 소개글 div 작성했습니다.
팀 소개 상세 내용, 폰트 및 폰트 크기, 정렬 등 구현
=> [Update] - 팀 소개 배경 및 소개글 작성 (실제 구현)

index.html, style/index.css
프로젝트 자체의 성격을 부각할 수 있는 세부 내용으로 작성
크기가 줄어듦에 따라 유동적으로 폰트 사이즈 및 포스터 이미지가 변화하도록 설정
=> [Update] - 팀 소개글 세부 내용 작성 및 화면 크기에 따른 위치 설정

src/review/review.js, style/review.css
- 다른 영화를 클릭했을 때 리뷰 창이 개별적으로 작동되도록 구분
- localStorage의 key를 영화 id와 작성자의 이름을 합쳐서 새로운 키 생성
- 상세 페이지의 영화가 맞는지를 검증한 이후 리뷰 출력
- 별점 선택 칸으로 변경
- prompt 창으로 비밀번호를 입력하게되면 별표(숨김처리)가 나오지 않음
- prompt 창에서 입력칸은 1개만 나옴
1. 비밀번호가 노출된 상태로 사용
2. 상세페이지 내에서 input 태그로 별표처리하여 비밀번호 입력
- 작성, 수정을 모두 모달창으로 구현
- 리뷰 작성 순으로 변경
- table 태그에서 insertRow(0) 함수로 리뷰 최신순으로 작성했으나 두번째 리뷰까지는 작동하나 세번째부터 꼬임
=> [Update] - 리뷰 작성 보완사항 기능 추가

movieDetail.html, src/similarMovies.js, style/similarMoviesStyle.css
- 1페이지 데이터를 가져와 포스터 사진이 존재하지않거나 , 오버뷰 내용이 존재하지 않는경우 제거하였습니다.
- 추천영화 데이터를 popularity 기준 정렬 하였습니다.
- 영화 더보기 버튼을 누를 시 순환하게됩니다 ( 마지막 목록에서 오른쪽 버튼 클릭시 첫번째 추천 영화 목록 으로 이동)
- 좌우 버튼 클릭시 애니메이션은 구현 하지 못했습니다.
=> [Update] - 추천영화 더보기 기능

movieDetail.html, src/review/review.js, style/review.css
- 삭제 버튼 클릭 후 비밀번호를 입력하여 해당 리뷰의 비밀번호와 일치하는지 확인하는 유효성 검사
- 일치하지않으면 alert 창으로 틀렸다고 알림
- 일치하면 해당 리뷰 삭제
- 수정 모달창 기능 구현
=> 60 update 수정 및 삭제 모달창 기능 구현

style/index.css
- 포스터 좌우 캐릭터 위치를 실제 웹페이지 출력 환경에서 동일한 영역에 위치하도록 수정
- 포스터 중앙 프로젝트 소개 문구 중앙정렬
- 검색 버튼 기본 색상을 background : white / text : black으로 수정
- 마우스 오버 시 background : red / text : white
=> 68 fix 배너 및 포스터 요소 배치 위치 수정

index.html, src/main.js, src/pagination/pagination.js, src/render.js, src/search/search.js, src/state.js, src/tmdb-api/api.js, style/index.css
- index.css 카드리스트를 만들기위한 수정.
- 포스터 이미지 사이즈가 100vw 일때 자꾸 아래에 스크롤바 생겨서 99로 변경.
- render.js 수정.
- search.js 수정.
- 코드 리팩토링 필요. (추후 디자인 컨펌시 진행.)
- 더보기 버튼 디자인.
=> 40 update 랜딩 페이지 카드 리스트 정렬 기능 구현

src/review/review.js
=> [Update] - 리뷰 작성 시 Validation Check 및 예외 처리

src/review/review.js
- 리뷰 작성 시 비밀번호 8자 이상 및 특수문자 포함 유효성 검사
- 글자와 숫자가 같이 있는 작성자의 이름도 예외처리를 하여 정규식 수정
- `const onlyNumberCheck = /^[0-9]*$/;`
=> [Update] - 리뷰 작성 시 Validation Check 및 예외 처리 추가

src/review/review.js, src/similarMovies.js
=> [Update] - 리뷰 작성 / 수정 시 리뷰 내용 공백, 별점 미기입 validation check

README.md
(소개글 입니다) 영화 추천 사이트 입니다.
- [Movolleh-Movie-Website](배포 링크)
(랜딩 페이지와 상세 페이지 구분하여 작성하였습니다)
- 헤더 : 클릭 시 홈으로 이동하는 홈(MOVOLLEH) 버튼, 웹 페이지를 제작한 팀을 소개하는 Credit 버튼, 영화를 검색할 수 있는 검색 창으로 구성되어 있습니다.
- 팀 소개글 : 웹 페이지를 소개하는 곳입니다.
- 영화 목록 : 인기 영화 순으로 나열되어 있으며, 검색 결과로 나타난 영화들이 나열됩니다.
- 헤더 : 클릭 시 홈으로 이동하는 X(ANVOLLEH) 버튼으로 구성되어 있습니다.
- 좌측 : 검색된 영화에 대한 정보 (영화 포스터, 제목, 내용 요약, 감독 및 출연진)와 리뷰를 나타냅니다.
- 우측 : 좌측 영화에 대한 추천 영화들이 나열됩니다.
(필수 요구사항 기준으로 작성하였습니다. 더 구체적으로 작성하는게 좋을지 의견 말씀해주세요)
- 바닐라 JS 사용
- TMDB Open API 이용
- Top Rated API, Details API, Credits API, Similar API
- 영화 정보 상세 페이지 구현
- 상세 페이지 영화 리뷰 작성 기능 구현
- UX를 고려한 validation check
- 하기 기재된 JavaScript 문법 요소 이용하여 구현
- (추가 예정)
- 페이지네이션 기능 구현
- CSS 반응형 UI 구현
- HTML
- CSS
- JavaScript
- src : JavaScript 폴더입니다.
- (JS 상세 파일 설명도 추가하는게 좋을지 의견 말씀해주세요)
- style : CSS …
=> [Update] - Readme.md 웹페이지 기능 구현 반영

README.md
Project Configuration 파일 설명 추가
<details>
<summary>src</summary>
<div markdown="1">
<ul>
<li>crewDetail : 상세 페이지 좌측 영화 상세 정보</li>
<li>modal.js : 랜딩 페이지 동적 페이지네이션 기능 구현</li>
<li>pagination.js : 랜딩 페이지 하단 페이지 버튼 이용하 특정 페이지 이동 기능</li>
<li>review.js : 상세 페이지 좌측 하단 리뷰 작성 기능 구현</li>
<li>search.js : 랜딩 페이지 우측 상단 검색 기능 구현</li>
<li>tmdb-api : TMDB API 요청을 처리</li>
<li>main.js : main JavaScript File</li>
<li>render.js : 랜딩 페이지 영화 렌더링 이전 페이지 초기화 기능 구현</li>
<li>similarMovies.js : 상세 페이지 우측 검색 영화 기반 인기도 순 추천 영화 목록 출력</li>
<li>state.js : 페이지네이션 상태 클래스 조정 </li>
</ul>
</div>
</details>
=> [Update] - Readme.md 내용 추가

index.html, style/index.css
=> 90 fix상세페이지 메인페이지 헤더 크기 통일

src/crewDetail/crewCard.js, src/render.js
=> hotfix - 배포시이미지가 노출되지 않음.

src/pagination/pagination.js, src/search/search.js
- 포스터 값이 null 인 영화의 경우 표시하지않도록 하였습니다.
=> [Update] - 포스터이미지가 없는 영화 제거

credit.html
- 깃허브 페이지와 동일한 README 를 구현했습니다.
=> [Update] - About us페이지 README 섹션 구현.
